// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs0uEMA-kObYkES6A4JCdXziRbAUUsGlA',
    appId: '1:655828864389:web:YOUR_WEB_APP_ID',
    messagingSenderId: '655828864389',
    projectId: 'waste-collection-truck-tracker',
    authDomain: 'waste-collection-truck-tracker.firebaseapp.com',
    storageBucket: 'waste-collection-truck-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0uEMA-kObYkES6A4JCdXziRbAUUsGlA',
    appId: '1:655828864389:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '655828864389',
    projectId: 'waste-collection-truck-tracker',
    storageBucket: 'waste-collection-truck-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0uEMA-kObYkES6A4JCdXziRbAUUsGlA',
    appId: '1:655828864389:ios:fd2641341e9d8d860f48ec',
    messagingSenderId: '655828864389',
    projectId: 'waste-collection-truck-tracker',
    storageBucket: 'waste-collection-truck-tracker.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0uEMA-kObYkES6A4JCdXziRbAUUsGlA',
    appId: '1:655828864389:ios:fd2641341e9d8d860f48ec',
    messagingSenderId: '655828864389',
    projectId: 'waste-collection-truck-tracker',
    storageBucket: 'waste-collection-truck-tracker.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );
}
